ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:$RUBY_VERSION AS base

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libyaml-dev \
    pkg-config \
    nodejs \
    npm \
    procps \
    graphviz \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN gem install foreman


COPY Gemfile* /app/
RUN bundle install
COPY package* /app/
RUN npm install
COPY . /app
